# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  commit-info:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say Hello"
          command: echo "Hello from CircleCI 👋"
      - run:
          name: "Show commit details"
          command: |
            echo "hello day"

workflows:
  version: 2
  commit-workflow:
    jobs:
      - commit-info
